language: node_js
node_js:
  - "8"
script:
  - npm run build
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    branch: master
  tag: latest

notifications:
  email: false
  webhooks: https://oapi.dingtalk.com/robot/send?access_token=5b98a99097a6427e1de786c8fa3052077a26e53587d687b7a521af79d1154aa2
